/* The 78-card Rider–Waite–Smith deck.
 * Meanings follow the RWS / Golden Dawn tradition. Elements for the Major
 * Arcana come from their Golden Dawn astrological attributions (planet or sign),
 * which is what the elemental-dignity method uses. */
(function () {
  'use strict';

  // [number, name, element, astrology, glyph, upright keywords, reversed keywords, upright meaning, reversed meaning]
  var MAJORS = [
    [0, 'The Fool', 'air', 'Uranus / Air', '\u2645',
      ['beginnings', 'innocence', 'leap of faith', 'spontaneity'],
      ['recklessness', 'hesitation', 'naivety', 'poor judgement'],
      'A fresh start with an open heart. You stand at the edge of something new, and the invitation is to trust the journey before you can see where it ends.',
      'A leap taken carelessly, or a leap you refuse to take. Check whether you are holding back out of fear or rushing forward without looking.'],
    [1, 'The Magician', 'air', 'Mercury', '☿',
      ['willpower', 'skill', 'manifestation', 'resourcefulness'],
      ['manipulation', 'untapped talent', 'scattered energy', 'trickery'],
      'Everything you need is already on the table. Focused intent turns ideas into reality, so name what you want and act on it.',
      'Talent going to waste, or power used to mislead. Someone, possibly you, is saying more than they can deliver.'],
    [2, 'The High Priestess', 'water', 'Moon', '☽',
      ['intuition', 'mystery', 'inner voice', 'hidden knowledge'],
      ['secrets', 'ignored instincts', 'surface thinking', 'withdrawal'],
      'The answer is not in the noise but in the quiet. Trust what you sense before you can prove it; something is still being revealed.',
      'You are overriding your intuition or something is being concealed. Listen inward instead of seeking outside approval.'],
    [3, 'The Empress', 'earth', 'Venus', '♀',
      ['abundance', 'nurturing', 'fertility', 'beauty'],
      ['smothering', 'creative block', 'dependence', 'neglect of self'],
      'Growth, comfort and creative fertility. What you tend with care is ready to flourish; let yourself receive as well as give.',
      'Care has become control, or you have stopped nourishing yourself. Creative energy is stuck and needs gentleness to return.'],
    [4, 'The Emperor', 'fire', 'Aries', '♈',
      ['structure', 'authority', 'stability', 'leadership'],
      ['rigidity', 'domination', 'lack of discipline', 'tyranny'],
      'Order, boundaries and leadership. This is a time to build structure, take responsibility and stand firmly in your own authority.',
      'Control has turned rigid or authority is being misused. Equally, a lack of structure may be the real problem.'],
    [5, 'The Hierophant', 'earth', 'Taurus', '♉',
      ['tradition', 'institutions', 'mentorship', 'shared belief'],
      ['rebellion', 'unconventional path', 'dogma', 'challenging norms'],
      'Learning within a tradition. A teacher, institution or tried-and-true method offers the guidance you need right now.',
      'The rules no longer fit. You may need to question received wisdom and find your own way of believing.'],
    [6, 'The Lovers', 'air', 'Gemini', '♊',
      ['love', 'union', 'values alignment', 'choice'],
      ['disharmony', 'misalignment', 'temptation', 'indecision'],
      'A meaningful union or a choice made from the heart. The question is less who or what you choose and more what you value.',
      'Values and actions have drifted apart. A relationship or decision is out of balance and needs honest attention.'],
    [7, 'The Chariot', 'water', 'Cancer', '♋',
      ['determination', 'willpower', 'victory', 'direction'],
      ['lack of direction', 'aggression', 'loss of control', 'obstacles'],
      'Victory through focus. Opposing forces can be harnessed if you hold the reins firmly and keep your eyes on the goal.',
      'Pulled in two directions at once. Without a clear aim, momentum turns into frustration.'],
    [8, 'Strength', 'fire', 'Leo', '♌',
      ['courage', 'compassion', 'inner strength', 'patience'],
      ['self-doubt', 'raw emotion', 'insecurity', 'force over gentleness'],
      'Quiet courage. Gentleness and patience tame what force never could, including your own wilder impulses.',
      'Self-doubt or anger is getting the upper hand. Reconnect with your own resilience before you act.'],
    [9, 'The Hermit', 'earth', 'Virgo', '♍',
      ['introspection', 'solitude', 'inner guidance', 'wisdom'],
      ['isolation', 'loneliness', 'withdrawal', 'lost direction'],
      'Step back from the crowd to find your own light. Solitude now brings clarity that busy days cannot.',
      'Retreat has become isolation, or you are avoiding the reflection you need. Balance solitude with connection.'],
    [10, 'Wheel of Fortune', 'fire', 'Jupiter', '♃',
      ['cycles', 'fate', 'turning point', 'luck'],
      ['bad luck', 'resisting change', 'repeating patterns', 'delay'],
      'The wheel turns. Circumstances are shifting in ways larger than you; meet the change and let it carry you forward.',
      'A downturn or a cycle stuck on repeat. Ask what pattern keeps returning and what part of it you can change.'],
    [11, 'Justice', 'air', 'Libra', '♎',
      ['fairness', 'truth', 'cause and effect', 'accountability'],
      ['injustice', 'dishonesty', 'avoiding accountability', 'bias'],
      'Truth and consequence. Decisions will be weighed fairly; act with integrity and the outcome will follow.',
      'Something is unfair or unexamined. Look honestly at your own part as well as others’.'],
    [12, 'The Hanged Man', 'water', 'Neptune / Water', '♆',
      ['surrender', 'pause', 'new perspective', 'letting go'],
      ['stalling', 'resistance', 'needless sacrifice', 'indecision'],
      'Pause and see things upside down. What looks like a delay is a chance to understand the situation in a new way.',
      'You are stuck because you will not let go, or you are sacrificing yourself for nothing. Make the decision you are avoiding.'],
    [13, 'Death', 'water', 'Scorpio', '♏',
      ['endings', 'transformation', 'transition', 'release'],
      ['resisting change', 'stagnation', 'fear of endings', 'lingering'],
      'An ending that clears the ground. Something has run its course; letting it go makes space for what comes next. Rarely literal.',
      'Clinging to what has already ended. Change is coming either way; resisting it only prolongs the discomfort.'],
    [14, 'Temperance', 'fire', 'Sagittarius', '♐',
      ['balance', 'moderation', 'patience', 'integration'],
      ['excess', 'imbalance', 'impatience', 'discord'],
      'The middle way. Blend opposites patiently, and something better than either will emerge in its own time.',
      'Too much of one thing, not enough of another. Re-establish balance before pushing forward.'],
    [15, 'The Devil', 'earth', 'Capricorn', '♑',
      ['attachment', 'temptation', 'materialism', 'shadow self'],
      ['release', 'breaking free', 'reclaiming power', 'awareness'],
      'Chains you could slip off if you chose. Look at the habits, relationships or desires that hold more power over you than they should.',
      'Breaking free. You are seeing the bind clearly and beginning to reclaim your freedom.'],
    [16, 'The Tower', 'fire', 'Mars', '♂',
      ['upheaval', 'sudden change', 'revelation', 'collapse'],
      ['averted disaster', 'fear of change', 'delayed collapse', 'inner upheaval'],
      'Sudden change brings down what was built on weak foundations. Painful, but it reveals the truth and frees you to rebuild.',
      'Avoiding an overdue collapse, or an upheaval happening quietly inside. The longer it is postponed, the harder it falls.'],
    [17, 'The Star', 'air', 'Aquarius', '♒',
      ['hope', 'renewal', 'inspiration', 'serenity'],
      ['despair', 'disconnection', 'lack of faith', 'discouragement'],
      'Hope after the storm. Healing is underway; let yourself believe in the future and be guided by quiet inspiration.',
      'Faith has dimmed. Small acts of self-care can rekindle the hope that feels lost right now.'],
    [18, 'The Moon', 'water', 'Pisces', '♓',
      ['illusion', 'intuition', 'uncertainty', 'the subconscious'],
      ['clarity returning', 'released fear', 'confusion lifting', 'repressed emotion'],
      'Not everything is as it seems. Move carefully through uncertainty, guided by intuition rather than fear.',
      'The fog is lifting. Fears and confusion begin to clear, though some truths may surface uncomfortably.'],
    [19, 'The Sun', 'fire', 'Sun', '☉',
      ['joy', 'success', 'vitality', 'clarity'],
      ['temporary gloom', 'overconfidence', 'dimmed joy', 'delayed success'],
      'Warmth, success and clarity. One of the most positive cards in the deck: things are going well and you are seen for who you are.',
      'The sun is behind a cloud, not gone. Joy is delayed or muted; reconnect with what makes you feel alive.'],
    [20, 'Judgement', 'fire', 'Fire / Pluto', '♇',
      ['awakening', 'reckoning', 'renewal', 'calling'],
      ['self-doubt', 'refusing the call', 'harsh self-judgement', 'stagnation'],
      'A wake-up call. Reflect on the past, forgive what needs forgiving and rise to answer a deeper calling.',
      'You hear the call but doubt yourself. Harsh self-judgement is keeping you from stepping into a new chapter.'],
    [21, 'The World', 'earth', 'Saturn', '♄',
      ['completion', 'wholeness', 'achievement', 'integration'],
      ['incompletion', 'shortcuts', 'lack of closure', 'delays'],
      'A cycle completes. You have come full circle and can celebrate what has been achieved before the next journey begins.',
      'Almost there. Loose ends or a missing piece stop you from feeling complete; finish what you started.']
  ];

  var SUITS = {
    wands: { name: 'Wands', element: 'fire', domain: 'action, ambition, creativity and passion', symbol: 'wand' },
    cups: { name: 'Cups', element: 'water', domain: 'emotion, love, relationships and intuition', symbol: 'cup' },
    swords: { name: 'Swords', element: 'air', domain: 'thought, communication, conflict and truth', symbol: 'sword' },
    pentacles: { name: 'Pentacles', element: 'earth', domain: 'money, work, the body and material security', symbol: 'pentacle' }
  };

  var RANKS = ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Page', 'Knight', 'Queen', 'King'];

  // [upright keywords, reversed keywords, upright meaning, reversed meaning] in rank order
  var MINORS = {
    wands: [
      [['inspiration', 'new venture', 'potential', 'spark'], ['delays', 'lack of motivation', 'false start'],
        'A spark of inspiration or a creative opportunity. Grab it while the energy is hot.',
        'The fire will not catch. Motivation is low or a new project keeps stalling.'],
      [['planning', 'future vision', 'decisions', 'discovery'], ['fear of the unknown', 'poor planning', 'playing safe'],
        'Looking out over the horizon. You are planning your next move and weighing a bigger world.',
        'Staying in familiar territory out of fear. Plans lack ambition or follow-through.'],
      [['expansion', 'foresight', 'momentum', 'progress'], ['obstacles', 'delays', 'limited vision'],
        'Your ships are coming in. Early efforts are paying off and the horizon is opening up.',
        'Progress is slower than expected. Unforeseen obstacles call for patience.'],
      [['celebration', 'homecoming', 'harmony', 'milestone'], ['instability', 'transition', 'tension at home'],
        'A joyful milestone. Celebrate with your community; there is real stability to rejoice in.',
        'A celebration feels hollow or home life is unsettled. Look at what needs repair.'],
      [['competition', 'conflict', 'rivalry', 'friction'], ['avoiding conflict', 'resolution', 'inner struggle'],
        'Clashing egos and competition. The struggle can sharpen you if it stays fair.',
        'Conflict is ending, or you are avoiding a disagreement that needs to happen.'],
      [['victory', 'recognition', 'confidence', 'success'], ['ego', 'fall from grace', 'lack of recognition'],
        'Public success and recognition. You have earned your moment in the spotlight.',
        'Success goes to the head, or the praise you hoped for does not come.'],
      [['defending', 'perseverance', 'standing your ground', 'challenge'], ['overwhelm', 'giving up', 'defensiveness'],
        'Holding your position against pressure. Your conviction is worth defending.',
        'Exhausted by constant defence. Decide which battles are actually worth fighting.'],
      [['speed', 'momentum', 'swift action', 'news'], ['delays', 'frustration', 'scattered energy'],
        'Things move quickly now. Messages, travel or rapid progress arrive all at once.',
        'Momentum stalls or rushes in the wrong direction. Slow down and redirect.'],
      [['resilience', 'persistence', 'last stand', 'boundaries'], ['exhaustion', 'paranoia', 'stubbornness'],
        'Battle-weary but nearly there. One last push carries you through.',
        'Running on empty. Rest is not defeat; protect your energy.'],
      [['burden', 'responsibility', 'overload', 'hard work'], ['delegation', 'release', 'collapse under strain'],
        'Carrying too much. Success has brought heavy responsibility.',
        'It is time to put some burdens down, or they will put you down.'],
      [['enthusiasm', 'exploration', 'free spirit', 'good news'], ['setbacks', 'hasty ideas', 'lack of direction'],
        'An eager beginner with exciting news or a new passion to explore.',
        'Ideas without follow-through. Enthusiasm burns out before it becomes anything.'],
      [['energy', 'adventure', 'impulsiveness', 'passion'], ['recklessness', 'haste', 'frustration'],
        'Charging ahead with passion and courage. Adventure calls.',
        'Rushing in without a plan. Impulsiveness creates chaos.'],
      [['confidence', 'warmth', 'determination', 'vibrancy'], ['jealousy', 'insecurity', 'demanding'],
        'Magnetic confidence and warmth. Own your power and lead by example.',
        'Confidence turns into jealousy or self-doubt. Reconnect with your own spark.'],
      [['vision', 'leadership', 'entrepreneur', 'boldness'], ['impulsive', 'overbearing', 'high expectations'],
        'A visionary leader who inspires others to act. Think big and take charge.',
        'Leadership becomes domineering, or the vision outruns the plan.']
    ],
    cups: [
      [['new love', 'compassion', 'emotional opening', 'intuition'], ['blocked emotion', 'emptiness', 'self-love needed'],
        'An overflowing heart. New love, new friendship or deep emotional renewal.',
        'Feelings are bottled up. Fill your own cup before pouring for others.'],
      [['partnership', 'mutual attraction', 'connection', 'unity'], ['imbalance', 'broken bond', 'tension'],
        'A meeting of equals. Mutual respect and attraction create a real bond.',
        'A relationship is out of balance, or communication has broken down.'],
      [['friendship', 'celebration', 'community', 'joy'], ['overindulgence', 'gossip', 'isolation'],
        'Celebrating with friends. Joy shared is joy multiplied.',
        'Too much partying, or a friendship soured by gossip or a third party.'],
      [['apathy', 'contemplation', 'missed offers', 'withdrawal'], ['new awareness', 'acceptance', 'motivation'],
        'Bored or discontent, you may be missing what is offered right in front of you.',
        'Waking from apathy. You are ready to accept a new opportunity.'],
      [['loss', 'grief', 'regret', 'disappointment'], ['acceptance', 'moving on', 'forgiveness'],
        'Mourning what was spilled. Grief is real, but two cups still stand behind you.',
        'Turning back toward what remains. Healing and forgiveness begin.'],
      [['nostalgia', 'childhood', 'innocence', 'kindness'], ['living in the past', 'leaving home', 'naivety'],
        'Sweet memories and simple kindness. Someone from the past may reappear.',
        'Romanticising the past keeps you from living now.'],
      [['choices', 'illusion', 'wishful thinking', 'fantasy'], ['clarity', 'decisive action', 'alignment'],
        'Many tempting options, not all of them real. Separate fantasy from possibility.',
        'The illusions fade and the right choice becomes clear.'],
      [['walking away', 'disillusionment', 'seeking deeper meaning'], ['fear of leaving', 'aimless drifting', 'trying again'],
        'Leaving behind what no longer fulfils you, even if it looks good on the surface.',
        'Afraid to walk away, or drifting without knowing what you are searching for.'],
      [['contentment', 'wishes fulfilled', 'satisfaction', 'gratitude'], ['smugness', 'dissatisfaction', 'materialism'],
        'The wish card. Contentment and satisfaction are within reach.',
        'Having what you wanted and still feeling empty. Look deeper than surface pleasure.'],
      [['harmony', 'family', 'emotional fulfilment', 'happiness'], ['disconnection', 'broken home', 'misaligned values'],
        'Lasting happiness and emotional fulfilment, often within family or home.',
        'The picture-perfect ideal is not the reality. Reconnect with what truly matters.'],
      [['creative offers', 'intuitive messages', 'curiosity', 'sensitivity'], ['emotional immaturity', 'creative block', 'escapism'],
        'A surprising message of the heart or a playful creative idea. Stay open.',
        'Emotional immaturity or daydreaming that avoids reality.'],
      [['romance', 'charm', 'following the heart', 'imagination'], ['moodiness', 'unrealistic', 'jealousy'],
        'A romantic invitation or a call to follow your heart.',
        'Moodiness or unrealistic expectations. Charm without substance.'],
      [['compassion', 'emotional security', 'intuition', 'calm'], ['insecurity', 'codependency', 'martyrdom'],
        'Emotionally wise and deeply caring. Trust your intuition and hold space for others.',
        'Giving so much you lose yourself. Emotional boundaries are needed.'],
      [['emotional balance', 'diplomacy', 'control', 'generosity'], ['manipulation', 'volatility', 'coldness'],
        'Calm mastery of emotion. Stay steady while others are swept away.',
        'Emotions suppressed or used to control. Steadiness has turned cold or volatile.']
    ],
    swords: [
      [['clarity', 'breakthrough', 'truth', 'new idea'], ['confusion', 'misinformation', 'clouded judgement'],
        'A breakthrough of clarity. The truth cuts through confusion.',
        'Muddled thinking or misinformation. Do not decide until the fog clears.'],
      [['stalemate', 'difficult decision', 'avoidance', 'truce'], ['indecision', 'information overload', 'lesser of two evils'],
        'Stuck between two options and refusing to look. Removing the blindfold is the first step.',
        'Overwhelmed by the choice. You know more than you admit.'],
      [['heartbreak', 'sorrow', 'grief', 'painful truth'], ['recovery', 'forgiveness', 'releasing pain'],
        'Heartbreak or a painful truth. It hurts because it matters.',
        'Healing from sorrow. The worst is passing.'],
      [['rest', 'recovery', 'contemplation', 'restoration'], ['burnout', 'restlessness', 'stagnation'],
        'Rest and recuperate. Withdraw briefly to restore your strength.',
        'Burnout, or resting so long that recovery becomes avoidance.'],
      [['conflict', 'defeat', 'winning at all costs', 'tension'], ['reconciliation', 'making amends', 'past resentment'],
        'A hollow victory. Ask whether winning this fight is worth what it costs.',
        'Ready to make peace, or still carrying resentment from an old fight.'],
      [['transition', 'moving on', 'leaving behind', 'calmer waters'], ['resistance to change', 'unfinished business', 'baggage'],
        'Moving toward calmer waters. Leave trouble behind, even if you carry some sadness with you.',
        'Unable to move on. Old baggage keeps you anchored to the shore.'],
      [['deception', 'strategy', 'stealth', 'getting away with it'], ['confession', 'conscience', 'coming clean'],
        'Strategy, secrecy or someone getting away with something. Be alert to deception.',
        'The truth comes out. A time to confess or to stop fooling yourself.'],
      [['restriction', 'self-imposed limits', 'victim mentality', 'trapped'], ['release', 'new perspective', 'self-acceptance'],
        'Feeling trapped, though the bindings are looser than they seem.',
        'Freeing yourself. You see the way out was there all along.'],
      [['anxiety', 'worry', 'nightmares', 'despair'], ['hope', 'reaching out', 'despair lifting'],
        'Sleepless with worry. The fear is often worse than the reality.',
        'The anxiety begins to lift. Share your worries; you need not face them alone.'],
      [['painful ending', 'rock bottom', 'betrayal', 'crisis'], ['recovery', 'regeneration', 'resisting an end'],
        'A painful ending that cannot go any lower. The only way now is up; dawn is on the horizon.',
        'Recovering from the worst, or prolonging an ending that has already happened.'],
      [['curiosity', 'new ideas', 'vigilance', 'thirst for knowledge'], ['gossip', 'all talk', 'scattered thinking'],
        'Curious, alert and full of questions. A good time to learn and investigate.',
        'Talk without action, or words used carelessly.'],
      [['ambition', 'fast thinking', 'drive', 'assertiveness'], ['impulsiveness', 'burnout', 'aggression'],
        'Charging toward the goal with sharp focus and determination.',
        'Rushing in carelessly. Haste and harsh words cause damage.'],
      [['independence', 'clear boundaries', 'direct communication', 'perception'], ['coldness', 'cruelty', 'bitterness'],
        'Clear-headed, honest and independent. Speak your truth directly and fairly.',
        'Clarity has turned cold or cutting. Soften without losing your honesty.'],
      [['intellectual power', 'authority', 'truth', 'ethics'], ['manipulation', 'abuse of power', 'cruelty'],
        'Rational authority and fair judgement. Lead with logic and ethics.',
        'Intellect used to manipulate or dominate. Watch for abuse of power.']
    ],
    pentacles: [
      [['opportunity', 'prosperity', 'new venture', 'manifestation'], ['lost opportunity', 'poor planning', 'scarcity'],
        'A seed of material opportunity: a job, an investment or a new start in the physical world.',
        'An opportunity slips through your fingers. Plan before you plant.'],
      [['balance', 'adaptability', 'juggling', 'priorities'], ['overwhelm', 'disorganisation', 'overcommitted'],
        'Juggling priorities with flexibility. Stay adaptable and you will keep it all in the air.',
        'Too many balls in the air. Something is about to drop.'],
      [['teamwork', 'collaboration', 'skill', 'learning'], ['disharmony', 'misalignment', 'working alone'],
        'Collaboration and craftsmanship. Your skills are recognised and teamwork builds something lasting.',
        'Poor teamwork or work that is not valued. Realign around shared goals.'],
      [['security', 'saving', 'control', 'conservatism'], ['fear of loss', 'releasing control', 'greed'],
        'Holding tightly to security. Stability matters, but not at the cost of growth.',
        'Releasing a tight grip on money or control, or a fear of loss turning into greed.'],
      [['hardship', 'loss', 'isolation', 'worry'], ['recovery', 'spiritual poverty', 'help arriving'],
        'Hard times and feeling left out in the cold. Help is nearer than you think; ask for it.',
        'Recovery from hardship begins. Doors open again.'],
      [['generosity', 'charity', 'giving and receiving', 'sharing'], ['strings attached', 'debt', 'one-sided charity'],
        'The flow of giving and receiving. Share your resources or accept support with grace.',
        'Generosity with strings attached, or an imbalance in who gives and who takes.'],
      [['patience', 'long-term view', 'investment', 'perseverance'], ['impatience', 'poor returns', 'wasted effort'],
        'Patiently waiting for the harvest. Assess your progress and keep investing.',
        'Frustration with slow results. Consider whether the effort is going in the right place.'],
      [['craftsmanship', 'diligence', 'mastery', 'skill development'], ['perfectionism', 'lack of focus', 'mediocrity'],
        'Dedicated practice toward mastery. Hard work and attention to detail pay off.',
        'Perfectionism or going through the motions. Reconnect with why the work matters.'],
      [['abundance', 'luxury', 'self-sufficiency', 'independence'], ['overwork', 'hustling', 'financial setbacks'],
        'Self-made comfort and independence. Enjoy the fruits of your labour.',
        'Working so hard you cannot enjoy what you have, or a setback to independence.'],
      [['legacy', 'wealth', 'family', 'long-term success'], ['family disputes', 'financial failure', 'loss of legacy'],
        'Lasting wealth and legacy. Security that extends across generations.',
        'Disputes over money or inheritance. A legacy under strain.'],
      [['ambition', 'study', 'diligence', 'new skill'], ['procrastination', 'lack of progress', 'learning from failure'],
        'A student with practical ambition. Learn the skill and the opportunity follows.',
        'Daydreaming about results without doing the study.'],
      [['hard work', 'routine', 'reliability', 'methodical'], ['boredom', 'stagnation', 'laziness'],
        'Steady, reliable progress. Slow and methodical wins this race.',
        'Stuck in a rut. Routine has become stagnation.'],
      [['nurturing', 'practicality', 'financial security', 'groundedness'], ['self-neglect', 'work-life imbalance', 'smothering'],
        'Practical care and a warm, abundant home. Grounded generosity.',
        'Caring for everything except yourself. Restore the balance between work and home.'],
      [['wealth', 'business', 'security', 'discipline'], ['greed', 'stubbornness', 'materialism'],
        'Material mastery and secure leadership. Success built on discipline.',
        'Obsessed with status or money. Stubbornly resisting what needs to change.']
    ]
  };

  // Golden Dawn decan attributions for the pip cards 2–10.
  var DECANS = {
    wands: ['Mars in Aries', 'Sun in Aries', 'Venus in Aries', 'Saturn in Leo', 'Jupiter in Leo', 'Mars in Leo', 'Mercury in Sagittarius', 'Moon in Sagittarius', 'Saturn in Sagittarius'],
    cups: ['Venus in Cancer', 'Mercury in Cancer', 'Moon in Cancer', 'Mars in Scorpio', 'Sun in Scorpio', 'Venus in Scorpio', 'Saturn in Pisces', 'Jupiter in Pisces', 'Mars in Pisces'],
    swords: ['Moon in Libra', 'Saturn in Libra', 'Jupiter in Libra', 'Venus in Aquarius', 'Mercury in Aquarius', 'Moon in Aquarius', 'Sun in Gemini', 'Mars in Gemini', 'Saturn in Gemini'],
    pentacles: ['Jupiter in Capricorn', 'Mars in Capricorn', 'Sun in Capricorn', 'Mercury in Taurus', 'Moon in Taurus', 'Saturn in Taurus', 'Sun in Virgo', 'Venus in Virgo', 'Mercury in Virgo']
  };

  var ROMAN = ['0', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI', 'XVII', 'XVIII', 'XIX', 'XX', 'XXI'];

  function cap(s) { return s.charAt(0).toUpperCase() + s.slice(1); }

  var deck = [];
  MAJORS.forEach(function (m) {
    deck.push({
      id: 'major-' + m[0],
      arcana: 'major',
      number: m[0],
      numeral: ROMAN[m[0]],
      name: m[1],
      element: m[2],
      astrology: m[3],
      glyph: m[4],
      keywords: { up: m[5], rev: m[6] },
      meaning: { up: m[7], rev: m[8] }
    });
  });

  Object.keys(SUITS).forEach(function (suit) {
    MINORS[suit].forEach(function (c, i) {
      var rank = i + 1;
      var court = rank > 10;
      deck.push({
        id: suit + '-' + rank,
        arcana: 'minor',
        suit: suit,
        rank: rank,
        rankName: RANKS[i],
        court: court,
        numeral: court ? RANKS[i].charAt(0) : (rank === 1 ? 'A' : String(rank)),
        name: RANKS[i] + ' of ' + SUITS[suit].name,
        element: SUITS[suit].element,
        astrology: rank >= 2 && rank <= 10 ? DECANS[suit][rank - 2] : (rank === 1 ? 'Root of ' + cap(SUITS[suit].element) : cap(SUITS[suit].element) + ' court'),
        keywords: { up: c[0], rev: c[1] },
        meaning: { up: c[2], rev: c[3] }
      });
    });
  });

  window.Tarot = window.Tarot || {};
  window.Tarot.DECK = deck;
  window.Tarot.SUITS = SUITS;
  window.Tarot.ROMAN = ROMAN;
})();
